# Generated by Django 3.1.3 on 2024-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='stock keeping unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
