# Generated by Django 3.1.3 on 2024-03-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240329_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(help_text='How many items are currently in stock'),
        ),
    ]
